[package]
name = "tidy-up-please-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-std = { version = "1.9.0", features = ["attributes"] }
sqlx = { version = "0.7", features = [ "mysql", "macros", "runtime-async-std", "tls-rustls", "time" ] }