[resource-not-found]
title = "${resource} not found"
detail = "Cannot find ${resource} with id ${resource_id}"

[internal-server-error]
title = "Internal Server Error"
detail = "The server encountered an unknown error. Please try again in a while."

[deserialization-error]
title = "Bad request body"
detail = "Request body you submitted is invalid. See errors below and correct request body."