[resource-not-found]
title = "${resource_type} not found"
detail = "Cannot find ${resource_type} with id '${resource_id}'"

[invalid-object-id]
title = "Bad request"
detail = "Provided ID '${provided_id}' is not valid ObjectID value. Provide correct value and try again."
